#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

lyra_root_dir=$(pwd)

npm install -g

test_dir=/tmp/lyra
blog_dir=$test_dir/blog
published_dir=$test_dir/published

cd $test_dir
cp "$lyra_root_dir/scripts/clear_test" $test_dir
./clear_test


mkdir -p $blog_dir $published_dir
git init --bare $published_dir

cd $blog_dir

lyra init -p $published_dir

lyra publish

cd $test_dir

echo "==> Feel free to explore"
ls

echo "--> cd $(pwd)"
